server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/hrm
    username: root
    password: 170803

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ngocngo8080@gmail.com
    password: rgczrzrcjxepufgl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "xZW6euEUqJQr6zVAK0ItGWD+FhORIYK5MeugElqypbgGjty3tRRFHhOuIHHNTNyx"
  expDuration: 7200
  refreshDuration: 360000

api:
  prefix: api/
